workflows:
  android-app:
    name: Android App
    max_build_duration: 30
    environment:
      java: 17
    scripts:
      - name: Set up Android
        script: sdkmanager --install "platform-tools" "platforms;android-34"
      - name: Build APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
