workflows:
  android-app:
    name: Android App
    max_build_duration: 30
    environment:
      java: 17
      android: latest
    scripts:
      - name: Build APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk


